### ISSUE TITLE
Time format?

### ISSUE THREAD

**Issue by wearelogik** [skiplagged/pokemongo-php#18]
Hello,

This is more of a question then an issue! What format is the time in? Is it a unix timestamp, miliseconds, microseconds?

Ex:
1469770531

**Comment by wdg** [comment]
public function getExpires() {
        $date = new DateTime();
        $date->setTimestamp($this->getExpiresTimestamp());
        return $date;
    }

    public function getExpiresTimestamp() {
        return $this->meta['expires'];
    }

And you can put that timestamp in strtotime and do wich format you need, default is (likely) a unix timestamp.

**Comment by wearelogik** [comment]
It's definitely a Unix Timestamp. But for some reason the Unix timestamp is not consistent. Multiple "scans" will reveal the same pokemon with deviating timestamp just seconds apart.

When a unix timestamp is defined it shouldn't change, ever! But why does it, in this case?

**Comment by aktarer** [comment]
Niantic's servers only provide seconds until expiration. We compute the timestamp from this information. As such, latency can make this crowdsourced information vary a little. Use pokemon id, latitude, and longitude for uniqueness. We'll probably patch our system with this soon anyways.

**Comment by wearelogik** [comment]
Would it be possible to include the "seconds until expiration" in the array instead of computing it first?
