### ISSUE TITLE
Caching login

### ISSUE THREAD

**Issue by baskettcase** [skiplagged/pokemongo-php#22]
Is there a way that I can cache the approved login session so that way when I refresh a couple minutes later that it won't have to go through the login process every time?

**Comment by aktarer** [comment]
Yeah, of course. Just add an if condition to the login line in example to only log in if it's been a while.

**Comment by baskettcase** [comment]
Ok I'll have to take a look further. It's not constantly running. Just through a Cron job. And part of the default routine is the login so I'll see what variables I need to make sure that it knows I am authorized. I was hoping you could help, but shouldn't be too hard to go through the code again :)
