### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by marvantes** [skiplagged/pokemongo-php#3]
Sorry, that im a noob in this but.. can you help me? i uploaded your package online and it throws a parse error.

`Parse error: syntax error, unexpected '[' in /data/web/virtuals/23010/virtual/www/domains/test.koderhtml.cz/pokego/Skiplagged.php on line 68`

**Comment by Narno** [comment]
"[]" array notation is supported in PHP >= 5.4.

**Comment by marvantes** [comment]
OK thanks :)

**Comment by marvantes** [comment]
@Narno did you tried this project yet? i cant get any pokemons in my city.. and it is a big city when i use pokevision i get some.. but when i use this.. empty array... what im doing wrong.. please help me :)

**Comment by Ceranimo** [comment]
This project doesn't support all countries i think. I got same issue for my country too.

**Comment by marvantes** [comment]
@Ceranimo i think thats bullshit.. in my country there is one city on their live map with pokemons :) but no other.. wtf is this.. :D

**Comment by marvantes** [comment]
im closing this cause its worked out... but starting a new one :)
