### ISSUE TITLE
Problem with getting pokemons 

### ISSUE THREAD

**Issue by marvantes** [skiplagged/pokemongo-php#4]
Hi, so the issue here is that we cant get pokemons on like 80% of the globe.... only on same points as your map does... what are we doing wrong?

**Comment by aktarer** [comment]
Not sure, what bounds are you using?

**Comment by marvantes** [comment]
@aktarer can u send me a example of Czech City with Pokémons like Prague or Ostrava?

**Comment by marvantes** [comment]
@aktarer ot define exact format of bounds... I can get new York but not los Angeles for example :) So it looks like your system supports only some cities....

**Comment by aktarer** [comment]
I just tried Ostrava, Czech Republic with `bounds=((49.723753599999995, 18.0964242), (49.9157291, 18.3783648))`...seems to be working fine.

![screenshot from 2016-07-24 13 20 39](https://cloud.githubusercontent.com/assets/841373/17085240/909e4538-51a1-11e6-9d6a-a6a0d7468089.png)

**Comment by rrallo** [comment]
I am having a similar. In the Bay Area I can only see pokemon in Fremont and Daly City. No pokemon in San Francisco.  If I zoom out really far on the globe I can see pokemon in certain specific cities, in dense clusters, but not around regular locations, even locations where you expect a lot of them like San Francisco.

Calling get on:

http://skiplagged.com/api/pokemon.php?address=Civic%20Center,%20San%20Francisco,%20California

Getting no elements. Am I mistaken here?

**Comment by aktarer** [comment]
I think there's a bit of misunderstanding. All the data on our live map is crowdsourced. You'd need to populate the areas you're interested in. That can be done via pokemongo-php, pokemongo-python, or our Android app: https://play.google.com/store/apps/details?id=com.skiplagged.pokemap

**Comment by marvantes** [comment]
Well i cant get your example working i can get player info but no Pokémons it sends: no pdata....

**Comment by rrallo** [comment]
So how can I help you guys input more data into the system, let my users log in with their account to your API from anywhere and that will automatically upload to you?
