### ISSUE TITLE
Example.php does not work

### ISSUE THREAD

**Issue by marvantes** [skiplagged/pokemongo-php#6]
I know im keeping you bussy... sorry..

Well ill describe the problem. Downloaded your package, uploaded online, changer username and password.  Its here: http://pokelocation.cz/example.php - look did you tried that PHP version? what am i doing wrong? its your clear project only with changed username and pass... 

Why it isnt working for me... i cant get anything...  when i put that `while(1)` away.. i could get player profile but when i tried get some pokemons even in your default loation: `$bounds = $client->getBoundsForAddress('central park, ny');` i failed... nothing... please help.

**Comment by aktarer** [comment]
Take a look at your php error log

**Comment by marvantes** [comment]
None... just checked.. 

http://pokelocation.cz/ this now is what i can get.. i have access to profile..  but cant look for pokemons.. it just spin the loading wheel and aftera a long time it crashes...

**Comment by marvantes** [comment]
Ok well i got it working.. but it takes soo much time do decompile pdata on your SKIPLAGGED_API, that is why my app didnt work.. is there a chance to give me that  http://skiplagged.com/api/pokemon.php file? so i can decompile the pdata by myself?
